import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css"/>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <h1>DollTrack</h1>
          <details>
            <summary>
              menu
            </summary>
            <ul>
              <li><a href="#">Dashboard</a></li>
              <li><a href="#">Logs and summaries</a></li>
              <li><a href="#">Statistics and charts</a></li>
              <li><a href="#">Budgets and goals</a></li>
              <li><a href="#">Settings</a></li>
            </ul>
          </details>
        </nav>
        {children}
      </body>
    </html>
  );
}
